version: '3.8'

services:
  qbittorrent-vpn:
    image: binhex/arch-qbittorrentvpn:latest
    container_name: qbittorrent-vpn
    privileged: true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - NET_ADMIN
    ports:
      - "${WEBUI_PORT:-8080}:8080"           # qBittorrent WebUI
      - "${PRIVOXY_PORT:-8118}:8118"         # Privoxy HTTP Proxy
      - "${SOCKS_PORT:-9118}:9118"           # microsocks SOCKS5 Proxy
      - "${TORRENT_PORT:-58946}:58946"       # BitTorrent TCP
      - "${TORRENT_PORT:-58946}:58946/udp"   # BitTorrent UDP
    volumes:
      - "${CONFIG_PATH:-./config}:/config"
      - "${DATA_VOLUME:-torrent}:/data"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      # VPN Configuration
      - VPN_ENABLED=${VPN_ENABLED:-yes}
      - VPN_CLIENT=${VPN_CLIENT:-wireguard}
      - VPN_PROV=${VPN_PROV:-custom}
      - VPN_USER=${VPN_USER:-}
      - VPN_PASS=${VPN_PASS:-}

      # Network Configuration
      - LAN_NETWORK=${LAN_NETWORK:-192.168.1.0/24}
      - NAME_SERVERS=${NAME_SERVERS:-1.1.1.1,1.0.0.1}

      # Proxy Configuration
      - ENABLE_PRIVOXY=${ENABLE_PRIVOXY:-yes}
      - ENABLE_SOCKS=${ENABLE_SOCKS:-yes}
      - SOCKS_USER=${SOCKS_USER:-admin}
      - SOCKS_PASS=${SOCKS_PASS:-socks}

      # Advanced Options
      - STRICT_PORT_FORWARD=${STRICT_PORT_FORWARD:-yes}
      - USERSPACE_WIREGUARD=${USERSPACE_WIREGUARD:-no}
      - ENABLE_STARTUP_SCRIPTS=${ENABLE_STARTUP_SCRIPTS:-no}
      - VPN_OPTIONS=${VPN_OPTIONS:-}
      - VPN_INPUT_PORTS=${VPN_INPUT_PORTS:-}
      - VPN_OUTPUT_PORTS=${VPN_OUTPUT_PORTS:-}

      # System Configuration
      - WEBUI_PORT=${WEBUI_PORT:-8080}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - UMASK=${UMASK:-002}
      - DEBUG=${DEBUG:-false}

    restart: unless-stopped

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  # Create named volume if using volume name instead of bind mount
  torrent:
    external: true
